version: '2.12.2'
services:

  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8802:3306"

  blog:
    container_name: php_apache
    image: php_img:latest
    build:
      context: ./
    volumes:
      - /Users/Malte/Code/phpblog/src/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db